[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18.17.0"
  # Força o Netlify a fazer um build limpo
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-cache"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações de cache
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[context.production.environment]
  NEXT_PUBLIC_BUILD_TIME = "${new Date().toISOString()}"

# Configuração da função agendada
[[functions]]
  directory = "netlify/functions"

# Agendamento para atualizar os votos a cada 10 segundos
[functions.updateVotes]
  schedule = "*/10 * * * * *" 