[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18.17.0"
  # Força o Netlify a fazer um build limpo
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-cache"
  NEXT_TELEMETRY_DISABLED = "1"
  # Força o Netlify a não usar cache
  NETLIFY_CACHE_DISABLED = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações de cache
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Headers específicos para a API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Headers gerais para assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[context.production.environment]
  NEXT_PUBLIC_BUILD_TIME = "${new Date().toISOString()}" 